//> using publish.organization "io.github.alexarchambault"
//> using publish.name "hello-scala-cli"
//> using publish.computeVersion "git:tag"
//> using publish.repository "central-s01"
//> using publish.license "Apache-2.0"
//> using publish.url "https://github.com/alexarchambault/hello-scala-cli"
//> using publish.versionControl "github:alexarchambault/hello-scala-cli"
//> using publish.developer "Alex Archambault|alexandre.archambault@gmail.com|https://github.com/alexarchambault"
//> using publish.ci.computeVersion "git:tag"
//> using publish.ci.repository "central-s01"
//> using publish.ci.user "env:PUBLISH_USER"
//> using publish.ci.password "env:PUBLISH_PASSWORD"
//> using publish.ci.secretKey "env:PUBLISH_SECRET_KEY"
//> using publish.ci.secretKeyPassword "env:PUBLISH_SECRET_KEY_PASSWORD"
